// Configuration des capteurs et moteurs
#pragma config(Sensor, S1,     touch,          sensorEV3_Touch) // Capteur de contact sur le port S1
#pragma config(Sensor, S2,     gyro,           sensorEV3_Gyro)  // Gyroscope sur le port S2
#pragma config(Motor,  motorA,          moteur,        tmotorEV3_Large, PIDControl, encoder) // Moteur principal sur le port A
//*!!Code automatically generated by 'ROBOTC' configuration wizard !!*//

// Inclusion des fichiers nécessaires pour les différentes fonctionnalités
#include "initialize.c";
#include "motorCharacterization.c";
#include "robotFixe.c";
#include "robotMobile.c";
#include "gyroRateCharacterization.c";

// Tâche interface pour afficher le menu et sélectionner le mode de fonctionnement du robot
task interface(){

	eraseDisplay(); // Effacer l'écran
	displayBigTextLine(3, " Pour Robot :"); // Afficher le titre
	displayCenteredTextLine(6, "Fixe -> Bouton gauche"); // Indiquer que le bouton gauche active le mode fixe
	displayCenteredTextLine(8, "Mobile -> Bouton Droit"); // Indiquer que le bouton droit active le mode mobile
	displayCenteredTextLine(14, "Quitter le programme");
	displayCenteredTextLine(15, "-> Bouton Rouge");

	// Attendre que l'utilisateur appuie sur le bouton gauche ou droit
	while(getButtonPress(buttonLeft) == 0 && getButtonPress(buttonRight) == 0){}

	// Si le bouton gauche est pressé, activer le mode fixe
	if(getButtonPress(buttonLeft) == 1){
		while(getButtonPress(buttonLeft) == 1){} // Attendre que l'utilisateur relâche le bouton

		initialize(); // Initialisation de la position du gyroscope et du moteur
		startTask(keepHeadingPID); // Lancer la tâche de suivi de consigne pour le mode fixe

	}
	// Si le bouton droit est pressé, activer le mode mobile
	else if(getButtonPress(buttonRight) == 1){
		while(getButtonPress(buttonRight) == 1){} // Attendre que l'utilisateur relâche le bouton

		resetGyro(S2);
		initialize(); // Initialisation de la position du gyroscope et du moteur
		startTask(keepHeadingPID2); // Lancer la tâche de suivi de consigne pour le mode mobile

	}
}

// Tâche principale pour gérer les interactions et surveiller les boutons
task main()
{
	startTask(interface); // Lancer la tâche interface pour afficher le menu

	while(true){ // Boucle infinie pour maintenir le programme en cours d'exécution

		// Si le bouton central est pressé, arrêter les tâches et revenir au menu principal
		if(getButtonPress(buttonEnter) == 1){
			stopTask(keepHeadingPID); // Arrêter la tâche de suivi de consigne fixe
			stopTask(watchButtons);    // Arrêter la tâche de surveillance des boutons en mode fixe
			stopTask(IHM);             // Arrêter l'interface utilisateur en mode fixe
			stopTask(keepHeadingPID2); // Arrêter la tâche de suivi de consigne mobile
			stopTask(watchButtons2);   // Arrêter la tâche de surveillance des boutons en mode mobile
			stopTask(IHM2);            // Arrêter l'interface utilisateur en mode mobile
			setMotorSpeed(motorA, 0);  // Mettre le moteur à l'arrêt
			startTask(interface);      // Relancer la tâche interface pour revenir au menu

		}
		// Si le capteur de contact est pressé, arrêter toutes les tâches
		else if(getTouchValue(S1) == 1){
			stopAllTasks(); // Arrêter toutes les tâches en cas d'appui sur le capteur de contact
		}
	}
}
